services:
  credito-db:
    image: postgres:17.5
    container_name: credito-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credito_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credito_db
    ports:
      - "5432:5432"
    networks:
      - consulta-creditos-network
networks:
  consulta-creditos-network:
    driver: "bridge"