services:
  credito-db:
    image: postgres:17.5
    container_name: credito-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credito_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credito_db
    ports:
      - "5432:5432"
    networks:
      - consulta-creditos-network

  credito-api:
    image: abimaelrsergio/creditoapi:0.0.1
    container_name: credito-api
    ports:
      - "8080:8080"
    depends_on:
      credito-db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: credito-api
      SPRING_DATASOURCE_URL: jdbc:postgresql://credito-db:5432/credito_db?serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - consulta-creditos-network

networks:
  consulta-creditos-network:
    driver: "bridge"