services:
  credito-db:
    image: postgres:17.5
    container_name: credito-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credito_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credito_db
    ports:
      - "5432:5432"
    networks:
      - consulta-creditos-network
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - consulta-creditos-network

  credito-api:
    image: abimaelrsergio/creditoapi:0.0.1
    container_name: credito-api
    ports:
      - "8080:8080"
    depends_on:
      credito-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: credito-api
      SPRING_DATASOURCE_URL: jdbc:postgresql://credito-db:5432/credito_db?serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - consulta-creditos-network

networks:
  consulta-creditos-network:
    driver: "bridge"